name: CI
on:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          persist-credentials: True

      - name: Install Packages
        working-directory: .
        run: yarn install

      - name: Prettier Check 
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check .
          same_commit: True
